@echo off
chcp 65001

set "ARQUIVO=%USERPROFILE%\repos\local\dados\FALCON_AUTHORIZATION.txt"
set "TABELA=CUR_ETHOS_FDW.FDW.FALCON_AUTHORIZATION_%USERNAME%"
set "TABELA=%TABELA: =_%"

echo Executando processo completo...
snowsql -c snow_conexoes -q "CREATE OR REPLACE TABLE %TABELA% (id_transacao STRING, organizacao STRING, num_crt STRING, data_transacao STRING, vlr_fat STRING, tpo STRING, num_mcc STRING, estabelecimento STRING, nome_estabelecimento STRING, score_master STRING, score_visa STRING, score_falcon STRING, moeda STRING, iso_pais STRING); PUT 'file://%ARQUIVO:\=/%' @~ AUTO_COMPRESS=FALSE OVERWRITE=TRUE; COPY INTO %TABELA% FROM @~/FALCON_AUTHORIZATION.txt FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER='\t' SKIP_HEADER=1); REMOVE @~/FALCON_AUTHORIZATION.txt; CREATE OR REPLACE TABLE CUR_ETHOS_FDW.FDW.FALCON_AUTHORIZATION_VAGNER_MICHELL AS SELECT ID_TRANSACAO, ORGANIZACAO, NUM_CRT, TO_TIMESTAMP(DATA_TRANSACAO, 'YYYY-MM-DD"T"HH24:MI:SS.FFTZH:TZM') DATA_TRANSACAO, to_decimal(vlr_fat, 10, 2) VLR_FAT, TPO, NUM_MCC, ESTABELECIMENTO,  NOME_ESTABELECIMENTO, TO_NUMBER(SCORE_MASTER) SCORE_MASTER, TO_NUMBER(SCORE_VISA) SCORE_VISA, TO_NUMBER(SCORE_FALCON) SCORE_FALCON, MOEDA, ISO_PAIS FROM %TABELA%; SELECT COUNT(*) as total_registros FROM %TABELA%; SELECT * FROM %TABELA% LIMIT 3"

pause